debug: false

server:
  port: 9000

spring:
  datasource:
#    url: jdbc:mysql://47.114.77.210:3316/pssm?allowMultiQueries=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true
    url: jdbc:mysql://127.0.0.1:3306/pssm?allowMultiQueries=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      idle-timeout: 60000
      maximum-pool-size: 100
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1

  servlet:
    multipart:
      max-file-size: 10MB #单个上传文件大小限制
      max-request-size: 100MB #单此请求文件大小限制

  application:
    name: api-core

  ##传入接口字符串日期转Date字段，时区设置
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true

#mybatis
mybatis:
  mapper-locations: classpath*:mapping/*.xml

#pageHelper分页插件
pagehelper:
  helper-dialect: mysql #oracle
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.cc.app: DEBUG

#系统登录设置
system:
  login-expire-time-app: 1 # 手机端登录时间有效期，天数
  login-expire-time-pc: 6 # PC端登录时间有效期.,小时
  phone-code-expire-time: 5 # 手机短信验证码有效期，分钟
  phone-code-interval-time: 60 # 发送短信验证码间隔时间，秒

#签发jwt私钥
jwt:
  secret: qwe123asd456zxc789
